theme: jekyll-theme-cayman
# Site wide configuration

title: Introducing the IndieWeb
locale: en_GB
description: Clear, simple guides to taking greater control of your data on the Web
logo: logo.svg
search: true
url: //indiewebguides.org

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-archives
  
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Calum Ryan
  avatar: profile_md.jpg
  email:
  disqus-shortname:
  twitter: indiewebcamp
  facebook: indiewebcamp
  github: calumryan
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Jekyll Archives
jekyll-archives:
  enabled: [tags]
  permalinks:
    tag: '/browse/:name/'

# Escape curly brackets
lcb: "{"
rcb: "}"